title: Geo-informatics for Agriculture
description: Training manual
theme: just-the-docs

url: https://krgreene.github.io/geo-info

aux_links:
  # Download as PDF: https://krgreene.github.io/geo-info/assets/Geo-informatics-for-Agriculture.pdf

favicon_ico: "/assets/gis_favicon.png"
