title: Geo-informatics for Agriculture
description: Training manual
theme: just-the-docs

url: https://krgreene.github.io/geo-info

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
