title: Geo-informatics for Agriculture
description: Training manual
theme: just-the-docs

url: https://krgreene.github.io/geo-info

aux_links:
  Download as PDF: /assets/Geo-Informatics-for-Agriculture.pdf
